#!/usr/local/bin/php
<?php
//入口文件
ini_set('display_errors', 0);
error_reporting(E_ERROR);

define('DS', DIRECTORY_SEPARATOR);
define("PROJECT_ROOT", __DIR__);
define("CONFIG_ROOT", PROJECT_ROOT .DS . 'config');
define('DEPLOY_ROOT', PROJECT_ROOT . DS . 'deploy');
define('STORAGE_ROOT', PROJECT_ROOT . DS . 'storage');
define('TMP_ROOT', STORAGE_ROOT . DS . 'tmp');

require PROJECT_ROOT . DS . '_ide_helper.php';
require PROJECT_ROOT . DS . 'bootstrap' . DS . 'autoload.php';
spl_autoload_register('autoload');
$app = new \App\Application(CONFIG_ROOT);
$app->bootConsole($argv);
$app->handleCommand();
